#!/usr/bin/env bash
#configuring  Nginx to listen on port 80 of all active IPv4 IPs
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
